// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers/ProtocolBuffers.h"

// @@protoc_insertion_point(imports)

@class udp_request_t;
@class udp_request_tBuilder;
@class udp_response_t;
@class udp_response_tBuilder;
@class udp_response_tData;
@class udp_response_tDataBuilder;


typedef NS_ENUM(SInt32, ad_type_t) {
  ad_type_tTxt = 1,
  ad_type_tImage = 2,
  ad_type_tFlash = 4,
};

BOOL ad_type_tIsValidValue(ad_type_t value);
NSString *NSStringFromad_type_t(ad_type_t value);

typedef NS_ENUM(SInt32, ad_class_t) {
  ad_class_tEmbedded = 1,
  ad_class_tFloat = 2,
  ad_class_tPaster = 3,
};

BOOL ad_class_tIsValidValue(ad_class_t value);
NSString *NSStringFromad_class_t(ad_class_t value);

typedef NS_ENUM(SInt32, network_type_t) {
  network_type_tDefaultNetworkType = 0,
  network_type_tWifi = 1,
  network_type_tTwoG = 2,
  network_type_tThreeG = 3,
  network_type_tFourG = 4,
  network_type_tFiveG = 5,
};

BOOL network_type_tIsValidValue(network_type_t value);
NSString *NSStringFromnetwork_type_t(network_type_t value);

typedef NS_ENUM(SInt32, request_data_type_t) {
  request_data_type_tJson = 1,
  request_data_type_tHtml = 2,
};

BOOL request_data_type_tIsValidValue(request_data_type_t value);
NSString *NSStringFromrequest_data_type_t(request_data_type_t value);

typedef NS_ENUM(SInt32, call_type_t) {
  call_type_tIncoming = 0,
  call_type_tOutgoing = 1,
};

BOOL call_type_tIsValidValue(call_type_t value);
NSString *NSStringFromcall_type_t(call_type_t value);

typedef NS_ENUM(SInt32, dialer_type_t) {
  dialer_type_tDtUnknown = 0,
  dialer_type_tDtFreeCallDirect = 1,
  dialer_type_tDtNormalCallDirect = 2,
  dialer_type_tDtAlwaysAsk = 3,
};

BOOL dialer_type_tIsValidValue(dialer_type_t value);
NSString *NSStringFromdialer_type_t(dialer_type_t value);


@interface AdRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define udp_request_t_ip @"ip"
#define udp_request_t_ch @"ch"
#define udp_request_t_v @"v"
#define udp_request_t_prt @"prt"
#define udp_request_t_at @"at"
#define udp_request_t_tu @"tu"
#define udp_request_t_adn @"adn"
#define udp_request_t_adclass @"adclass"
#define udp_request_t_nt @"nt"
#define udp_request_t_rt @"rt"
#define udp_request_t_w @"w"
#define udp_request_t_h @"h"
#define udp_request_t_city @"city"
#define udp_request_t_addr @"addr"
#define udp_request_t_longtitude @"longtitude"
#define udp_request_t_latitude @"latitude"
#define udp_request_t_other_phone @"otherPhone"
#define udp_request_t_call_type @"callType"
#define udp_request_t_token @"token"
#define udp_request_t_tn @"tn"
#define udp_request_t_open_free_call @"openFreeCall"
#define udp_request_t_dialer_type @"dialerType"
#define udp_request_t_cached_adid @"cachedAdid"
@interface udp_request_t : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasOpenFreeCall_:1;
  BOOL hasLongtitude_:1;
  BOOL hasLatitude_:1;
  BOOL hasPrt_:1;
  BOOL hasIp_:1;
  BOOL hasCh_:1;
  BOOL hasV_:1;
  BOOL hasTu_:1;
  BOOL hasCity_:1;
  BOOL hasAddr_:1;
  BOOL hasOtherPhone_:1;
  BOOL hasToken_:1;
  BOOL hasTn_:1;
  BOOL hasCachedAdid_:1;
  BOOL hasAdn_:1;
  BOOL hasW_:1;
  BOOL hasH_:1;
  BOOL hasAt_:1;
  BOOL hasAdclass_:1;
  BOOL hasNt_:1;
  BOOL hasRt_:1;
  BOOL hasCallType_:1;
  BOOL hasDialerType_:1;
  BOOL openFreeCall_:1;
  Float32 longtitude;
  Float32 latitude;
  UInt64 prt;
  NSString* ip;
  NSString* ch;
  NSString* v;
  NSString* tu;
  NSString* city;
  NSString* addr;
  NSString* otherPhone;
  NSString* token;
  NSString* tn;
  NSString* cachedAdid;
  UInt32 adn;
  UInt32 w;
  UInt32 h;
  ad_type_t at;
  ad_class_t adclass;
  network_type_t nt;
  request_data_type_t rt;
  call_type_t callType;
  dialer_type_t dialerType;
}
- (BOOL) hasIp;
- (BOOL) hasCh;
- (BOOL) hasV;
- (BOOL) hasPrt;
- (BOOL) hasAt;
- (BOOL) hasTu;
- (BOOL) hasAdn;
- (BOOL) hasAdclass;
- (BOOL) hasNt;
- (BOOL) hasRt;
- (BOOL) hasW;
- (BOOL) hasH;
- (BOOL) hasCity;
- (BOOL) hasAddr;
- (BOOL) hasLongtitude;
- (BOOL) hasLatitude;
- (BOOL) hasOtherPhone;
- (BOOL) hasCallType;
- (BOOL) hasToken;
- (BOOL) hasTn;
- (BOOL) hasOpenFreeCall;
- (BOOL) hasDialerType;
- (BOOL) hasCachedAdid;
@property (readonly, strong) NSString* ip;
@property (readonly, strong) NSString* ch;
@property (readonly, strong) NSString* v;
@property (readonly) UInt64 prt;
@property (readonly) ad_type_t at;
@property (readonly, strong) NSString* tu;
@property (readonly) UInt32 adn;
@property (readonly) ad_class_t adclass;
@property (readonly) network_type_t nt;
@property (readonly) request_data_type_t rt;
@property (readonly) UInt32 w;
@property (readonly) UInt32 h;
@property (readonly, strong) NSString* city;
@property (readonly, strong) NSString* addr;
@property (readonly) Float32 longtitude;
@property (readonly) Float32 latitude;
@property (readonly, strong) NSString* otherPhone;
@property (readonly) call_type_t callType;
@property (readonly, strong) NSString* token;
@property (readonly, strong) NSString* tn;
- (BOOL) openFreeCall;
@property (readonly) dialer_type_t dialerType;
@property (readonly, strong) NSString* cachedAdid;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (udp_request_tBuilder*) builder;
+ (udp_request_tBuilder*) builder;
+ (udp_request_tBuilder*) builderWithPrototype:(udp_request_t*) prototype;
- (udp_request_tBuilder*) toBuilder;

+ (udp_request_t*) parseFromData:(NSData*) data;
+ (udp_request_t*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (udp_request_t*) parseFromInputStream:(NSInputStream*) input;
+ (udp_request_t*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (udp_request_t*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (udp_request_t*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface udp_request_tBuilder : PBGeneratedMessageBuilder {
@private
  udp_request_t* resultUdpRequestT;
}

- (udp_request_t*) defaultInstance;

- (udp_request_tBuilder*) clear;
- (udp_request_tBuilder*) clone;

- (udp_request_t*) build;
- (udp_request_t*) buildPartial;

- (udp_request_tBuilder*) mergeFrom:(udp_request_t*) other;
- (udp_request_tBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (udp_request_tBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasIp;
- (NSString*) ip;
- (udp_request_tBuilder*) setIp:(NSString*) value;
- (udp_request_tBuilder*) clearIp;

- (BOOL) hasCh;
- (NSString*) ch;
- (udp_request_tBuilder*) setCh:(NSString*) value;
- (udp_request_tBuilder*) clearCh;

- (BOOL) hasV;
- (NSString*) v;
- (udp_request_tBuilder*) setV:(NSString*) value;
- (udp_request_tBuilder*) clearV;

- (BOOL) hasPrt;
- (UInt64) prt;
- (udp_request_tBuilder*) setPrt:(UInt64) value;
- (udp_request_tBuilder*) clearPrt;

- (BOOL) hasAt;
- (ad_type_t) at;
- (udp_request_tBuilder*) setAt:(ad_type_t) value;
- (udp_request_tBuilder*) clearAt;

- (BOOL) hasTu;
- (NSString*) tu;
- (udp_request_tBuilder*) setTu:(NSString*) value;
- (udp_request_tBuilder*) clearTu;

- (BOOL) hasAdn;
- (UInt32) adn;
- (udp_request_tBuilder*) setAdn:(UInt32) value;
- (udp_request_tBuilder*) clearAdn;

- (BOOL) hasAdclass;
- (ad_class_t) adclass;
- (udp_request_tBuilder*) setAdclass:(ad_class_t) value;
- (udp_request_tBuilder*) clearAdclass;

- (BOOL) hasNt;
- (network_type_t) nt;
- (udp_request_tBuilder*) setNt:(network_type_t) value;
- (udp_request_tBuilder*) clearNt;

- (BOOL) hasRt;
- (request_data_type_t) rt;
- (udp_request_tBuilder*) setRt:(request_data_type_t) value;
- (udp_request_tBuilder*) clearRt;

- (BOOL) hasW;
- (UInt32) w;
- (udp_request_tBuilder*) setW:(UInt32) value;
- (udp_request_tBuilder*) clearW;

- (BOOL) hasH;
- (UInt32) h;
- (udp_request_tBuilder*) setH:(UInt32) value;
- (udp_request_tBuilder*) clearH;

- (BOOL) hasCity;
- (NSString*) city;
- (udp_request_tBuilder*) setCity:(NSString*) value;
- (udp_request_tBuilder*) clearCity;

- (BOOL) hasAddr;
- (NSString*) addr;
- (udp_request_tBuilder*) setAddr:(NSString*) value;
- (udp_request_tBuilder*) clearAddr;

- (BOOL) hasLongtitude;
- (Float32) longtitude;
- (udp_request_tBuilder*) setLongtitude:(Float32) value;
- (udp_request_tBuilder*) clearLongtitude;

- (BOOL) hasLatitude;
- (Float32) latitude;
- (udp_request_tBuilder*) setLatitude:(Float32) value;
- (udp_request_tBuilder*) clearLatitude;

- (BOOL) hasOtherPhone;
- (NSString*) otherPhone;
- (udp_request_tBuilder*) setOtherPhone:(NSString*) value;
- (udp_request_tBuilder*) clearOtherPhone;

- (BOOL) hasCallType;
- (call_type_t) callType;
- (udp_request_tBuilder*) setCallType:(call_type_t) value;
- (udp_request_tBuilder*) clearCallType;

- (BOOL) hasToken;
- (NSString*) token;
- (udp_request_tBuilder*) setToken:(NSString*) value;
- (udp_request_tBuilder*) clearToken;

- (BOOL) hasTn;
- (NSString*) tn;
- (udp_request_tBuilder*) setTn:(NSString*) value;
- (udp_request_tBuilder*) clearTn;

- (BOOL) hasOpenFreeCall;
- (BOOL) openFreeCall;
- (udp_request_tBuilder*) setOpenFreeCall:(BOOL) value;
- (udp_request_tBuilder*) clearOpenFreeCall;

- (BOOL) hasDialerType;
- (dialer_type_t) dialerType;
- (udp_request_tBuilder*) setDialerType:(dialer_type_t) value;
- (udp_request_tBuilder*) clearDialerType;

- (BOOL) hasCachedAdid;
- (NSString*) cachedAdid;
- (udp_request_tBuilder*) setCachedAdid:(NSString*) value;
- (udp_request_tBuilder*) clearCachedAdid;
@end

#define udp_response_t_data @"data"
#define udp_response_t_error_code @"errorCode"
@interface udp_response_t : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasErrorCode_:1;
  UInt32 errorCode;
  NSMutableArray * dataArray;
}
- (BOOL) hasErrorCode;
@property (readonly, strong) NSArray * data;
@property (readonly) UInt32 errorCode;
- (udp_response_tData*)dataAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (udp_response_tBuilder*) builder;
+ (udp_response_tBuilder*) builder;
+ (udp_response_tBuilder*) builderWithPrototype:(udp_response_t*) prototype;
- (udp_response_tBuilder*) toBuilder;

+ (udp_response_t*) parseFromData:(NSData*) data;
+ (udp_response_t*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (udp_response_t*) parseFromInputStream:(NSInputStream*) input;
+ (udp_response_t*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (udp_response_t*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (udp_response_t*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

#define Data_sid @"sid"
#define Data_adid @"adid"
#define Data_brand @"brand"
#define Data_title @"title"
#define Data_desc @"desc"
#define Data_curl @"curl"
#define Data_edurl @"edurl"
#define Data_material @"material"
@interface udp_response_tData : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasSid_:1;
  BOOL hasBrand_:1;
  BOOL hasTitle_:1;
  BOOL hasDesc_:1;
  BOOL hasCurl_:1;
  BOOL hasEdurl_:1;
  BOOL hasMaterial_:1;
  BOOL hasAdid_:1;
  NSString* sid;
  NSString* brand;
  NSString* title;
  NSString* desc;
  NSString* curl;
  NSString* edurl;
  NSString* material;
  UInt32 adid;
}
- (BOOL) hasSid;
- (BOOL) hasAdid;
- (BOOL) hasBrand;
- (BOOL) hasTitle;
- (BOOL) hasDesc;
- (BOOL) hasCurl;
- (BOOL) hasEdurl;
- (BOOL) hasMaterial;
@property (readonly, strong) NSString* sid;
@property (readonly) UInt32 adid;
@property (readonly, strong) NSString* brand;
@property (readonly, strong) NSString* title;
@property (readonly, strong) NSString* desc;
@property (readonly, strong) NSString* curl;
@property (readonly, strong) NSString* edurl;
@property (readonly, strong) NSString* material;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (udp_response_tDataBuilder*) builder;
+ (udp_response_tDataBuilder*) builder;
+ (udp_response_tDataBuilder*) builderWithPrototype:(udp_response_tData*) prototype;
- (udp_response_tDataBuilder*) toBuilder;

+ (udp_response_tData*) parseFromData:(NSData*) data;
+ (udp_response_tData*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (udp_response_tData*) parseFromInputStream:(NSInputStream*) input;
+ (udp_response_tData*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (udp_response_tData*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (udp_response_tData*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface udp_response_tDataBuilder : PBGeneratedMessageBuilder {
@private
  udp_response_tData* resultData;
}

- (udp_response_tData*) defaultInstance;

- (udp_response_tDataBuilder*) clear;
- (udp_response_tDataBuilder*) clone;

- (udp_response_tData*) build;
- (udp_response_tData*) buildPartial;

- (udp_response_tDataBuilder*) mergeFrom:(udp_response_tData*) other;
- (udp_response_tDataBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (udp_response_tDataBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSid;
- (NSString*) sid;
- (udp_response_tDataBuilder*) setSid:(NSString*) value;
- (udp_response_tDataBuilder*) clearSid;

- (BOOL) hasAdid;
- (UInt32) adid;
- (udp_response_tDataBuilder*) setAdid:(UInt32) value;
- (udp_response_tDataBuilder*) clearAdid;

- (BOOL) hasBrand;
- (NSString*) brand;
- (udp_response_tDataBuilder*) setBrand:(NSString*) value;
- (udp_response_tDataBuilder*) clearBrand;

- (BOOL) hasTitle;
- (NSString*) title;
- (udp_response_tDataBuilder*) setTitle:(NSString*) value;
- (udp_response_tDataBuilder*) clearTitle;

- (BOOL) hasDesc;
- (NSString*) desc;
- (udp_response_tDataBuilder*) setDesc:(NSString*) value;
- (udp_response_tDataBuilder*) clearDesc;

- (BOOL) hasCurl;
- (NSString*) curl;
- (udp_response_tDataBuilder*) setCurl:(NSString*) value;
- (udp_response_tDataBuilder*) clearCurl;

- (BOOL) hasEdurl;
- (NSString*) edurl;
- (udp_response_tDataBuilder*) setEdurl:(NSString*) value;
- (udp_response_tDataBuilder*) clearEdurl;

- (BOOL) hasMaterial;
- (NSString*) material;
- (udp_response_tDataBuilder*) setMaterial:(NSString*) value;
- (udp_response_tDataBuilder*) clearMaterial;
@end

@interface udp_response_tBuilder : PBGeneratedMessageBuilder {
@private
  udp_response_t* resultUdpResponseT;
}

- (udp_response_t*) defaultInstance;

- (udp_response_tBuilder*) clear;
- (udp_response_tBuilder*) clone;

- (udp_response_t*) build;
- (udp_response_t*) buildPartial;

- (udp_response_tBuilder*) mergeFrom:(udp_response_t*) other;
- (udp_response_tBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (udp_response_tBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)data;
- (udp_response_tData*)dataAtIndex:(NSUInteger)index;
- (udp_response_tBuilder *)addData:(udp_response_tData*)value;
- (udp_response_tBuilder *)setDataArray:(NSArray *)array;
- (udp_response_tBuilder *)clearData;

- (BOOL) hasErrorCode;
- (UInt32) errorCode;
- (udp_response_tBuilder*) setErrorCode:(UInt32) value;
- (udp_response_tBuilder*) clearErrorCode;
@end


// @@protoc_insertion_point(global_scope)
