//
//  TPAnalyticConstants.h
//  TouchPalDialer
//
//  Created by Chen Lu on 9/3/12.
//  Copyright (c) 2012 CooTek. All rights reserved.
//

/*SECTION ALIPAY*/
#define EV_ALIPAY_CLIENT_INSTALL_OK @"EV_ALIPAY_CLIENT_INSTALL_OK"
#define EV_ALIPAY_CLIENT_INSTALL_CANCEL @"EV_ALIPAY_CLIENT_INSTALL_CANCEL"
#define EV_ALIPAY_JUMP_TO_ALIPAY @"EV_ALIPAY_JUMP_TO_ALIPAY"

/*SECTION SMTEYE*/
#define EV_SMTEYE_UI_SHOWN @"EV_SMTEYE_UI_SHOWN"
#define EV_SMTEYE_SEARCH_CALL_SUM @"EV_SMTEYE_SEARCH_CALL_SUM"
#define EV_SMTEYE_SEARCH_CALL_ON_RESULT @"EV_SMTEYE_SEARCH_CALL_ON_RESULT"
//Attribute key
#define SEARCH_STR_LENGTH @"SEARCH_STR_LENGTH"
#define EV_SMTEYE_SEARCH_CALL_ON_MAIN @"EV_SMTEYE_SEARCH_CALL_ON_MAIN"
#define EV_SMTEYE_SEARCH_CALL_ON_BRANCH @"EV_SMTEYE_SEARCH_CALL_ON_BRANCH"

#define EV_SMTEYE_UI_SHOWN_MAIN_STORE @"EV_SMTEYE_UI_SHOWN_MAIN_STORE"
#define EV_SMTEYE_UI_SHOWN_BRANCH_STORE @"EV_SMTEYE_UI_SHOWN_BRANCH_STORE"

#define EV_SMTEYE_KEY_DEL_CLICK @"EV_SMTEYE_KEY_DEL_CLICK"
#define EV_SMTEYE_KEYBOARD_CLICK @"EV_SMTEYE_KEYBOARD_CLICK"

/*SECTION UNKNOWN CONTACT DETAIL*/
#define EV_UNKNOWN_DETAIL_LIST_ADD @"EV_UNKNOWN_DETAIL_LIST_ADD"
#define EV_UNKNOWN_DETAIL_BUTTON_ADD @"EV_UNKNOWN_DETAIL_BUTTON_ADD"

/*SECTION MARKETING*/
#define EV_MARKET_ACTIVITY_UI_SHOWN @"EV_MARKET_ACTIVITY_UI_SHOWN"
#define EV_APP_ACTIVATE @"EV_APP_ACTIVATE"

/*SECTION JB*/
#define EV_LAUNCH_WITH_TWEAK @"EV_LAUNCH_WITH_TWEAK"
//Attribute key
#define EVAT_TWEAK_VERSION @"TWEAK_VERSION"

/*SECTION SKIN*/
#define EV_SKIN_INVESTIGATE @"EV_SKIN_INVESTIGATE"
#define EVAT_SKIN_SATISFY @"SKIN_SATISFY"
#define EVAT_SKIN_UNSATISFY_REASON @"SKIN_UNSATISFY_REASON"

#define EV_USAGE @"EV_USAGE"
#define EV_SKIN_USAGE @"EV_SKIN_USAGE"
#define EVAT_CURRENT_SKIN @"CURRENT_SKIN"

/*SECTION THEME*/
#define EV_THEME_CLICK_DOWNLOAD @"EV_THEME_CLICK_DOWNLOAD"
//Attribute key
#define EVAT_THEME_NAME @"THEME_NAME"

/*SECTION DOWNLOAD*/
#define EV_DOWNLOAD_START @"EV_DOWNLOAD_START"
#define EV_DOWNLOAD_CANCEL @"EV_DOWNLOAD_CANCEL"
#define EV_DOWNLOAD_FINISHED @"EV_DOWNLOAD_FINISHED"
#define EV_DOWNLOAD_FAILED @"EV_DOWNLOAD_FAILED"
//Attribute key
#define EVAT_DOWNLOAD_ID @"DOWNLOAD_ID"
#define EVAT_DOWNLOAD_ERROR @"DOWNLOAD_ERROR"

/*SECTION ADDSHOP*/
#define EV_ADDSHOP_WITHID @"EV_ADDSHOP_WITHID"
#define EV_ADDSHOP_WITHOUTID @"EV_ADDSHOP_WITHOUTID"

/*SECTION LOG*/
#define EV_SMTEYELOG_NETWORK_IDENTIFIED @"EV_SMTEYELOG_NETWORK_IDENTIFIED"
#define EV_SMTEYELOG_NETWORK_UNIDENTIFIED @"EV_SMTEYELOG_NETWORK_UNIDENTIFIED"
#define EV_SMTEYELOG_LOCAL_IDENTIFIED @"EV_SMTEYELOG_LOCAL_IDENTIFIED"
#define EV_SMTEYELOG_LOCAL_UNIDENTIFIED @"EV_SMTEYELOG_LOCAL_UNIDENTIFIED"

/*SECTION LONGPRESS*/
#define EV_LONG_PRESS @"EV_LONG_PRESS"
#define EVLB_LONG_PRESS_PAGE @"LONG_PRESS_PAGE_"
#define EV_LONG_PRESS_EXECUTE @"EV_LONG_PRESS_EXECUTE"
#define EVLB_LONG_PRESS_EXECUTE_ACTION @"LONG_PRESS_EXECUTE_ACTION_"

/*SECTION MAKE CALL*/
#define EV_MAKE_CALL @"EV_MAKE_CALL"
#define EVLB_MAKE_CALL_FROM_SOURCE @"MAKE_CALL_FROM_SOURCE_"

/*SECTION FAVOR*/
#define EV_ENTER_FAVOR @"EV_ENTER_FAVOR"
#define EVAT_FAVOR_COUNT @"FAVOR_COUNT"

/*SECTION SMART DIALER*/
#define EV_SMART_DIALER_ON @"EV_SMART_DIALER_ON"
#define EV_SMART_DIALER_RULE_ON @"EV_SMART_DIALER_RULE_ON"
#define EVLB_SMART_DIALER_RULE_NAME @"SMART_DIALER_RULE_NAME"

/*SECTION CALL BLOCK*/
#define EV_CALLBLOCK_SET_STATUS @"EV_CALLBLOCK_SET_STATUS"

/*SECTION VOTE PLUGIN*/
#define EV_VOTE_PLUGIN @"EV_VOTE_PLUGIN"

/*SECTION WEIXIN */
#define EV_WEIXIN_SHARE @"EV_WEIXIN_SHARE"
#define EV_WEIXIN_TOOL_ICON_CLICKED @"EV_WEIXIN_TOOL_ICON_CLICKED"
#define EV_WEIXIN_MSG_ICON_CLICKED @"EV_WEIXIN_MSG_ICON_CLICKED"

/*SECTION CALLER_TELL_UGC*/
#define EV_CALLER_TELL_UGC_TAG_TOTAL @"EV_CALLER_TELL_UGC_TAG_TOTAL"
#define EV_CALLER_TELL_UGC_TAG_TOTAL_SUCCESS @"EV_CALLER_TELL_UGC_TAG_TOTAL_SUCCESS"
#define EV_CALLER_TELL_UGC_CANCEL_TAG @"EV_CALLER_TELL_UGC_CANCEL_TAG"
#define EV_CALLER_TELL_UGC_RETAG @"EV_CALLER_TELL_UGC_RETAG"
#define EV_CALLER_TELL_UGC_RETAG_SUCCESS @"EV_CALLER_TELL_UGC_RETAG_SUCCESS"
#define EV_CALLER_TELL_UGC_UNKNOWN_DETAIL_TAG @"EV_CALLER_TELL_UGC_UNKNOWN_DETAIL_TAG"
#define EV_CALLER_TELL_UGC_LONGPRESS_TAG @"EV_CALLER_TELL_UGC_LONGPRESS_TAG"
#define EV_CALLER_TELL_UGC_CALLLOG_TAGBUTTON_PRESS @"EV_CALLER_TELL_UGC_CALLLOG_TAGBUTTON_PRESS"
#define EV_CALLER_TELL_UGC_NOTIFICATION_TAG_SUCESS @"EV_CALLER_TELL_UGC_NOTIFICATION_TAG_SUCESS"
#define EV_CALLER_TELL_UGC_SURVEY_NEWTAG_SUCCESS @"EV_CALLER_TELL_UGC_SURVEY_NEWTAG_SUCCESS"
#define EV_CALLER_TELL_UGC_SURVEY_SHOW_BY_OUTGOINGCALL @"EV_CALLER_TELL_UGC_SURVEY_SHOW_BY_OUTGOINGCALL"
#define EV_CALLER_TELL_UGC_SURVEY_SHOW_BY_INCOMINGCALL @"EV_CALLER_TELL_UGC_SURVEY_SHOW_BY_INCOMINGCALL"
#define EV_CALLER_TELL_UGC_SURVEY_SHOW_BY_INCOMINGCALL_NATIONAL @"EV_CALLER_TELL_UGC_SURVEY_SHOW_BY_INCOMINGCALL_NATIONAL"
#define EV_CALLER_TELL_UGC_SURVEY_SHOW_BY_INCOMINGCALL_VERIFIED_SHOP @"EV_CALLER_TELL_UGC_SURVEY_SHOW_BY_INCOMINGCALL_VERIFIED_SHOP"
#define EV_CALLER_TELL_UGC_SURVEY_SHOW_BY_INCOMINGCALL_NORMAL_SHOP @"EV_CALLER_TELL_UGC_SURVEY_SHOW_BY_INCOMINGCALL_NORMAL_SHOP"
#define EV_CALLER_TELL_UGC_SURVEY_SHOW_BY_OUTGOINGCALL_NATIONAL @"EV_CALLER_TELL_UGC_SURVEY_SHOW_BY_INCOMINGCALL_NATIONAL"
#define EV_CALLER_TELL_UGC_SURVEY_SHOW_BY_OUTGOINGCALL_VERIFIED_SHOP @"EV_CALLER_TELL_UGC_SURVEY_SHOW_BY_INCOMINGCALL_VERIFIED_SHOP"
#define EV_CALLER_TELL_UGC_SURVEY_SHOW_BY_OUTGOINGCALL_NORMAL_SHOP @"EV_CALLER_TELL_UGC_SURVEY_SHOW_BY_INCOMINGCALL_NORMAL_SHOP"
#define EV_CALLER_TELL_UGC_SURVEY_SHOW_AND_NOT_KNOW @"EV_CALLER_TELL_UGC_SURVEY_SHOW_AND_NOT_KNOW"
#define EV_CALLER_TELL_UGC_SURVEY_SHOW_AND_CONFIRM @"EV_CALLER_TELL_UGC_SURVEY_SHOW_AND_CONFIRM"
#define EV_CALLER_TELL_UGC_SURVEY_SHOW_AND_NOT_CONFIRM @"EV_CALLER_TELL_UGC_SURVEY_SHOW_AND_NOT_CONFIRM"

/*SECTION REDESIGN*/
#define EV_LONG_GESTURE_ON_DIALER @"EV_LONG_GESTURE_ON_DIALER"

#define EV_COMMAND_ADD_TO_CONTACT @"EV_COMMAND_ADD_TO_CONTACT"
#define EV_COMMAND_REMOVE_CALLS @"EV_COMMAND_REMOVE_CALLS"
#define EV_COMMAND_SEND_SMS @"EV_COMMAND_SEND_SMS"
#define EV_COMMAND_MORE @"EV_COMMAND_MORE"
#define EV_COMMAND_MAKE_CALL @"EV_COMMAND_MAKE_CALL"
#define EV_COMMAND_DELETE_CONTACT @"EV_COMMAND_DELETE_CONTACT"
#define EV_COMMAND_EDIT_CONTACT @"EV_COMMAND_EDIT_CONTACT"
#define EV_COMMAND_COPY_NUMBER @"EV_COMMAND_COPY_NUMBER"
#define EV_COMMAND_SHARE_CONTACT @"EV_COMMAND_SHARE_CONTACT"
#define EV_COMMAND_ADD_TO_FAV @"EV_COMMAND_ADD_TO_FAV"
#define EV_COMMAND_EDIT_TO_CALL @"EV_COMMAND_EDIT_TO_CALL"

#define EV_UNKNOWN_MAKE_CALL @"EV_UNKNOWN_MAKE_CALL"
#define EV_UNKNOWN_SEND_SMS @"EV_UNKNOWN_SEND_SMS"
#define EV_UNKNOWN_SHARE_CONTACT @"EV_UNKNOWN_SHARE_CONTACT"
#define EV_UNKNOWN_COPY_NUMBER @"EV_UNKNOWN_COPY_NUMBER"

#define EV_KNOWN_GESTURE @"EV_KNOWN_GESTURE"
#define EV_KNOWN_SEND_MESSAGE @"EV_KNOWN_SEND_MESSAGE"
#define EV_KNOWN_ALIPAY @"EV_KNOWN_ALIPAY"
#define EV_KNOWN_SHARE_CONTACT @"EV_KNOWN_SHARE_CONTACT"
#define EV_KNOWN_ADD_TO_FAV @"EV_KNOWN_ADD_TO_FAV"
#define EV_KNOWN_REMOVE_FROM_FAV @"EV_KNOWN_REMOVE_FROM_FAV"
#define EV_KNOWN_SELECT_GROUP @"EV_KNOWN_SELECT_GROUP"
#define EV_KNOWN_MAKE_NOTE @"EV_KNOWN_MAKE_NOTE"

#define EV_PULLDOWN_GESTURE_ON_DIALER @"EV_PULLDOWN_GESTURE_ON_DIALER"
#define EV_PULLDOWN_ASSISTANT_ON_DIALER @"EV_PULLDOWN_ASSISTANT_ON_DIALER"
#define EV_PULLDOWN_THEMES_ON_DIALER @"EV_PULLDOWN_THEMES_ON_DIALER"
#define EV_PULLDOWN_SETTINGS_ON_DIALER @"EV_PULLDOWN_SETTINGS_ON_DIALER"

#define EV_PULLDOWN_ADD_TO_FAVOR_ON_CONTACT @"EV_PULLDOWN_ADD_TO_FAVOR_ON_CONTACT"
#define EV_PULLDOWN_SEND_BY_GROUP_ON_CONTACT @"EV_PULLDOWN_SEND_BY_GROUP_ON_CONTACT"
#define EV_PULLDOWN_DELETE_CONTACT_ON_CONTACT @"EV_PULLDOWN_DELETE_CONTACT_ON_CONTACT"
#define EV_PULLDOWN_SETTING_ON_CONTACT @"EV_PULLDOWN_SETTING_ON_CONTACT"

#define EV_ADD_CONTACT_ON_CONTACT @"EV_ADD_CONTACT_ON_CONTACT"

#define EV_ALL_CONTACTS_ON_SMART @"EV_ALL_CONTACTS_ON_SMART"
#define EV_MY_GROUP_ON_SMART @"EV_MY_GROUP_ON_SMART"
#define EV_CITIES_GROUP_ON_SMART @"EV_CITIES_GROUP_ON_SMART"
#define EV_COMPANY_GROUP_ON_SMART @"EV_COMPANY_GROUP_ON_SMART"
#define EV_LATEST_ADD_ON_SMART @"EV_LATEST_ADD_ON_SMART"
#define EV_NOTE_GROUP_ON_SMART @"EV_NOTE_GROUP_ON_SMART"

#define EV_SEARCH_ON_SMART @"EV_SEARCH_ON_SMART"

#define EV_LONG_GESTURE_ON_SMART @"EV_LONG_GESTURE_ON_SMART"

#define EV_MAKE_PHONE_COUNT @"EV_MAKE_PHONE_COUNT"
#define EV_MAKE_PHONE_WITH_IP_COUNT @"EV_MAKE_PHONE_WITH_IP_COUNT"
#define EV_MAKE_PHONE_BY_GESTURE_COUNT @"EV_MAKE_PHONE_BY_GESTURE_COUNT"

#define EV_CLEAR_RECORD_ON_DIALER @"EV_CLEAR_RECORD_ON_DIALER"
#define EV_GROUP_MANAGE_ON_SMART @"EV_GROUP_MANAGE_ON_SMART"
#define EV_CLICK_FAV_CELL_ON_SMART @"EV_CLICK_FAV_CELL_ON_SMART"
#define EV_MAKE_PHONE_IN_FAV_ON_SMART @"EV_MAKE_PHONE_IN_FAV_ON_SMART"
#define EV_SEND_SMS_IN_FAV_ON_SMART @"EV_SEND_SMS_IN_FAV_ON_SMART"

#define EV_DETAIL_IN_FAV_ON_SMART @"EV_DETAIL_IN_FAV_ON_SMART"
#define EV_MY_GROUP_ADD_MEMBER @"EV_MY_GROUP_ADD_MEMBER"
#define EV_MY_GROUP_REMOVE_MEMBER @"EV_MY_GROUP_REMOVE_MEMBER"

#define EV_OPEN_UDID_GOT @"EV_OPEN_UDID_GOT"


//
#define EV_SHAREGUIDE_COUNT @"EV_SHARERING_GUIDE_COUNT"
#define RING_GUIDE @"RING_GUIDE"
//VOIP
#define EV_VOIP_SHARE @"en_voip_share"

#define EV_VOIP_SHARE_SINGLE_SMS @"EV_VOIP_SHARE_SINGLE_SMS"
#define EV_VOIP_SHARE_SINGLE_WECHAT @"EV_VOIP_SHARE_SINGLE_WECHAT"
#define EV_VOIP_SHARE_SINGLE_COPY @"EV_VOIP_SHARE_SINGLE_COPY"
#define EV_VOIP_SHARE_TIMELINE_WECHAT @"EV_VOIP_SHARE_TIMELINE_WECHAT"
#define EV_VOIP_SHARE_QZONE_QQ @"EV_VOIP_SHARE_QZONE_QQ"
#define EV_VOIP_SHARE_SINGLE_QQ @"EV_VOIP_SHARE_SINGLE_QQ"
#define EV_VOIP_CALL @"EV_VOIP_CALL"
#define EV_VOIP_REGISTER_ENTER @"EV_VOIP_REGISTER_ENTER"
#define EV_VOIP_CANCEL_NO_REGISTER_INPUT @"EV_VOIP_CANCEL_NO_REGISTER_INPUT"
#define EV_VOIP_VERIFY_SEND @"EV_VOIP_VERIFY_SEND"
#define EV_VOIP_VERIFY_SUCCESS @"EV_VOIP_VERIFY_SUCCESS"
#define EV_VOIP_CALL_ERROR @"EV_VOIP_CALL_ERROR"
#define EV_VOIP_REGISGTER @"EV_VOIP_REGISTER"
//YELLOW
#define EV_YELLOWPAGE_REGISTER_ENTER @"EV_YELLOWPAGE_REGISTER_ENTER"
#define EV_YELLOWPAGE_INDEX_TAB_SELECTED @"EV_YELLOWPAGE_INDEX_TAB_SELECTED"
#define EV_YELLOWPAGE_CITY_ITEM @"EV_YELLOWPAGE_CITY_ITEM"
#define EV_YELLOWPAGE_SEARCH_ITEM @"EV_YELLOWPAGE_SEARCH_ITEM"
#define EV_YELLOWPAGE_CATEGORY_ITEM @"EV_YELLOWPAGE_CATEGORY_ITEM"
#define EV_YELLOWPAGE_RECOMMEND_ITEM @"EV_YELLOWPAGE_RECOMMEND_ITEM"
#define EV_YELLOWPAGE_BANNER_ITEM @"EV_YELLOWPAGE_BANNER_ITEM"
#define EV_YELLOWPAGE_ANNOUNCEMENT_ITEM @"EV_YELLOWPAGE_ANNOUNCEMENT_ITEM"
#define EV_YELLOWPAGE_SUB_BANNER_ITEM @"EV_YELLOWPAGE_SUB_BANNER_ITEM"
#define EV_YELLOWPAGE_ZIP_UPDATE @"EV_YELLOWPAGE_ZIP_UPDATE"
#define EV_YELLOWPAGE_FIND_ITEM @"EV_YELLOWPAGE_FIND_ITEM"
#define EV_YELLOWPAGE_NEW_CATEGORY_ITEM @"EV_YELLOWPAGE_NEW_CATEGORY_ITEM"
#define EV_YELLOWPAGE_CATEGORY_CONTENT_ITEM @"EV_YELLOWPAGE_CATEGORY_CONTENT_ITEM"
#define EV_YELLOWPAGE_COUPON_ITEM @"EV_YELLOWPAGE_COUPON_ITEM"
#define EV_YELLOWPAGE_GPS @"EV_YELLOWPAGE_GPS"
#define EV_YELLOWPAGE_PN_BOTTOM_BTN @"EV_YELLOWPAGE_PN_BOTTOM_BTN"
#define EV_YELLOWPAGE_PN_LIST_ITEM @"EV_YELLOWPAGE_PN_LIST_ITEM"
#define EV_YELLOWPAGE_PN_MESSAGE_ITEM @"EV_YELLOWPAGE_PN_MESSAGE_ITEM"
#define EV_YELLOWPAGE_PN_BTN @"EV_YELLOWPAGE_PN_BTN"
#define EV_YELLOWPAGE_BOTTOM_BAR_ITEM @"EV_YELLOWPAGE_BOTTOM_BAR_ITEM"
#define EV_YELLOWPAGE_ANNOUNCE_WEATHER_ITEM @"EV_YELLOWPAGE_ANNOUNCE_WEATHER_ITEM"
#define EV_YELLOWPAGE_PAGE_LOAD @"EV_YELLOWPAGE_PAGE_LOAD"
#define EV_YELLOWPAGE_FIND_TOP_RIGHT_ITEM @"EV_YELLOWPAGE_FIND_TOP_RIGHT_ITEM"
#define EV_YELLOWPAGE_FIND_NEWS_ITEM @"EV_YELLOWPAGE_FIND_NEWS_ITEM"
#define EV_YELLOWPAGE_SUBBANER_ITEM @"EV_YELLOWPAGE_SUBBANER_ITEM"
#define EV_YELLOWPAGE_PAGE_INDEX_FONT_FAIL_LOAD_FROM_FILE @"EV_YELLOWPAGE_PAGE_INDEX_FONT_FAIL_LOAD_FROM_FILE"
#define EV_YELLOWPAGE_MINI_BANNER_ITEM @"EV_YELLOWPAGE_MINI_BANNER_ITEM"
#define EV_YELLOWPAGE_MINI_BANNER_TAB_ICON_ITEM @"EV_YELLOWPAGE_MINI_BANNER_TAB_ICON_ITEM"
#define EV_YELLOWPAGE_FULL_AD_TAB_ICON_ITEM @"EV_YELLOWPAGE_FULL_AD_TAB_ICON_ITEM"
#define EV_YELLOWPAGE_FULL_AD_CLICK @"EV_YELLOWPAGE_FULL_AD_CLICK"
#define EV_YELLOWPAGE_FULL_AD_CLOSE @"EV_YELLOWPAGE_FULL_AD_CLOSE"
#define EV_YELLOWPAGE_SEND_TO_DESK_TOP_CLICK @"EV_YELLOWPAGE_SEND_TO_DESK_TOP_CLICK"
#define EV_YELLOWPAGE_OPEN_URL_FROM_DESK_TOP @"EV_YELLOWPAGE_OPEN_URL_FROM_DESK_TOP"
#define EV_EDURL_SCROLL_REMOVE @"EV_EDURL_SCROLL_REMOVE"
#define EV_YELLOWPAGE_STAT_KEY_MSG_RECEIVED @"EV_STAT_KEY_MSG_RECEIVED"
#define EV_YELLOWPAGE_STAT_KEY_MSG_CLICKED @"EV_STAT_KEY_MSG_CLICKED"
#define EV_YELLOWPAGE_STAT_KEY_AD_FUWUHAO_CLICKED @"EV_STAT_KEY_AD_FUWUHAO_CLICKED"
#define EV_YELLOWPAGE_CLICK_PROFIT_TASK @"EV_YELLOWPAGE_CLICK_PROFIT_TASK"
#define EV_YELLOWPAGE_CLICK_PROFIT_BUTTON @"EV_YELLOWPAGE_CLICK_PROFIT_BUTTON"
#define EV_YELLOWPAGE_CLICK_PROFIT_VIP @"EV_YELLOWPAGE_CLICK_PROFIT_VIP"
#define EV_YELLOWPAGE_CLICK_PROFIT_COIN @"EV_YELLOWPAGE_CLICK_PROFIT_COIN"
#define EV_YELLOWPAGE_CLICK_PROFIT_MINUTES @"EV_YELLOWPAGE_CLICK_PROFIT_MINUTES"
#define EV_YELLOWPAGE_CLICK_PROFIT_TRAFFIC @"EV_YELLOWPAGE_CLICK_PROFIT_TRAFFIC"
#define EV_YELLOWPAGE_CLICK_PROFIT_CARD @"EV_YELLOWPAGE_CLICK_PROFIT_CARD"

#define EV_YELLOWPAGE_JAVASCRIPT_START_NATIVE_ITEM @"EV_YELLOWPAGE_JAVASCRIPT_START_NATIVE_ITEM"
#define EV_VOIP_ENTER @"EV_VOIP_ENTER"
#define EV_AD_ACTIVATE @"EV_AD_ACTIVATE"
#define EV_VOIP_CALL_ERROR @"EV_VOIP_CALL_ERROR"
#define EV_VOIP_CALL_SUCCESS @"EV_VOIP_CALL_SUCCESS"

//FEEDS



//FLOW
#define EV_FLOW_ENTER @"EV_FLOW_ENTER"
#define EV_FLOW_ENTER_SUCCESS @"EV_FLOW_ENTER_SUCCESS"
#define EV_FLOW_PUSH_REDBAG @"EV_FLOW_PUSH_REDBAG"
#define EV_FLOW_EXCHANGE_TRAFFIC @"EV_FLOW_EXCHANGE_TRAFFIC"
#define EV_FLOW_SHOW_FINISH_TASK @"EV_FLOW_SHOW_FINISH_TASK"
#define EV_FLOW_EXCHANGE_BY_TAOBAO @"EV_FLOW_EXCHANGE_BY_TAOBAO"
#define EV_FLOW_OPEN_BY_TAOBAO @"EV_FLOW_OPEN_BY_TAOBAO"
#define EV_FLOW_STREAM_PAGE @"EV_FLOW_STREAM_PAGE"
#define EV_FLOW_SHOW_INPUTNAME_VIEW @"EV_FLOW_SHOW_INPUTNAME_VIEW"
#define EV_FLOW_INPUTNAME_VIEW_BACK_NO_INPUT @"EV_FLOW_INPUTNAME_VIEW_BACK_NO_INPUT"
#define EV_FLOW_INPUTNAME_VIEW_BACK_HAS_INPUT @"EV_FLOW_INPUTNAME_VIEW_BACK_HAS_INPUT"
#define EV_FLOW_INPUTNAME_VIEW_SUBMIT_PRESS @"EV_FLOW_INPUTNAME_VIEW_SUBMIT_PRESS"
#define EV_FLOW_INPUTNAME_VIEW_SUBMIT_FAIL @"EV_FLOW_INPUTNAME_VIEW_SUBMIT_FAIL"
#define EV_FLOW_INPUTNAME_VIEW_SUBMIT_SUCCESS @"EV_FLOW_INPUTNAME_VIEW_SUBMIT_SUCCESS"
#define EV_FLOW_EXCHANGE_VIEW_ALL_FINISH_X_PRESS @"EV_FLOW_EXCHANGE_VIEW_ALL_FINISH_X_PRESS"

#define EV_FLOW_RESULT_VIEW_CODE_2000 @"EV_FLOW_RESULT_VIEW_CODE_2000"
#define EV_FLOW_RESULT_VIEW_CODE_4321 @"EV_FLOW_RESULT_VIEW_CODE_4321"
#define EV_FLOW_RESULT_VIEW_CODE_4322 @"EV_FLOW_RESULT_VIEW_CODE_4322"
#define EV_FLOW_RESULT_VIEW_CODE_4324 @"EV_FLOW_RESULT_VIEW_CODE_4324"
#define EV_FLOW_RESULT_VIEW_CODE_4325 @"EV_FLOW_RESULT_VIEW_CODE_4325"
#define EV_FLOW_RESULT_VIEW_CODE_4328 @"EV_FLOW_RESULT_VIEW_CODE_4328"
#define EV_FLOW_RESULT_VIEW_CODE_4329 @"EV_FLOW_RESULT_VIEW_CODE_4329"
#define EV_FLOW_RESULT_VIEW_CODE_4326 @"EV_FLOW_RESULT_VIEW_CODE_4326"
#define EV_FLOW_RESULT_VIEW_CODE_4327 @"EV_FLOW_RESULT_VIEW_CODE_4327"
#define EV_FLOW_RESULT_VIEW_CODE_4330 @"EV_FLOW_RESULT_VIEW_CODE_4330"
#define EV_FLOW_RESULT_VIEW_CODE_4004 @"EV_FLOW_RESULT_VIEW_CODE_4004"
#define EV_FLOW_RESULT_VIEW_CODE_ELSE @"EV_FLOW_RESULT_VIEW_CODE_ELSE"

#define EV_FLOW_RESULT_VIEW_SURE_BUTTON_CODE_2000 @"EV_FLOW_RESULT_VIEW_SURE_BUTTON_CODE_2000"
#define EV_FLOW_RESULT_VIEW_SURE_BUTTON_CODE_4321 @"EV_FLOW_RESULT_VIEW_SURE_BUTTON_CODE_4321"
#define EV_FLOW_RESULT_VIEW_SURE_BUTTON_CODE_4322 @"EV_FLOW_RESULT_VIEW_SURE_BUTTON_CODE_4322"
#define EV_FLOW_RESULT_VIEW_SURE_BUTTON_CODE_4324 @"EV_FLOW_RESULT_VIEW_SURE_BUTTON_CODE_4324"
#define EV_FLOW_RESULT_VIEW_SURE_BUTTON_CODE_4325 @"EV_FLOW_RESULT_VIEW_SURE_BUTTON_CODE_4325"
#define EV_FLOW_RESULT_VIEW_SURE_BUTTON_CODE_4328 @"EV_FLOW_RESULT_VIEW_SURE_BUTTON_CODE_4328"
#define EV_FLOW_RESULT_VIEW_SURE_BUTTON_CODE_4329 @"EV_FLOW_RESULT_VIEW_SURE_BUTTON_CODE_4329"
#define EV_FLOW_RESULT_VIEW_SURE_BUTTON_CODE_4326 @"EV_FLOW_RESULT_VIEW_SURE_BUTTON_CODE_4326"
#define EV_FLOW_RESULT_VIEW_SURE_BUTTON_CODE_4330 @"EV_FLOW_RESULT_VIEW_SURE_BUTTON_CODE_4330"
#define EV_FLOW_RESULT_VIEW_SURE_BUTTON_CODE_ELSE @"EV_FLOW_RESULT_VIEW_SURE_BUTTON_CODE_ELSE"

#define EV_FLOW_RESULT_VIEW_X_PRESS_CODE_2000 @"EV_FLOW_RESULT_VIEW_X_PRESS_CODE_2000"
#define EV_FLOW_RESULT_VIEW_X_PRESS_CODE_4321 @"EV_FLOW_RESULT_VIEW_X_PRESS_CODE_4321"
#define EV_FLOW_RESULT_VIEW_X_PRESS_CODE_4322 @"EV_FLOW_RESULT_VIEW_X_PRESS_CODE_4322"
#define EV_FLOW_RESULT_VIEW_X_PRESS_CODE_4324 @"EV_FLOW_RESULT_VIEW_X_PRESS_CODE_4324"
#define EV_FLOW_RESULT_VIEW_X_PRESS_CODE_4325 @"EV_FLOW_RESULT_VIEW_X_PRESS_CODE_4325"
#define EV_FLOW_RESULT_VIEW_X_PRESS_CODE_4328 @"EV_FLOW_RESULT_VIEW_X_PRESS_CODE_4328"
#define EV_FLOW_RESULT_VIEW_X_PRESS_CODE_4329 @"EV_FLOW_RESULT_VIEW_X_PRESS_CODE_4329"
#define EV_FLOW_RESULT_VIEW_X_PRESS_CODE_4326 @"EV_FLOW_RESULT_VIEW_X_PRESS_CODE_4326"
#define EV_FLOW_RESULT_VIEW_X_PRESS_CODE_4330 @"EV_FLOW_RESULT_VIEW_X_PRESS_CODE_4330"
#define EV_FLOW_RESULT_VIEW_X_PRESS_CODE_ELSE @"EV_FLOW_RESULT_VIEW_X_PRESS_CODE_ELSE"

#define EV_FLOW_RESULT_VIEW_SUCCESS_SURE_BUTTON_PRESS @"EV_FLOW_RESULT_VIEW_SUCCESS_SURE_BUTTON_PRESS"
#define EV_FLOW_RESULT_VIEW_FAIL_SURE_BUTTON_PRESS @"EV_FLOW_RESULT_VIEW_FAIL_SURE_BUTTON_PRESS"
#define EV_FLOW_RESULT_VIEW_SUCCESS_X_PRESS @"EV_FLOW_RESULT_VIEW_SUCCESS_X_PRESS"
#define EV_FLOW_RESULT_VIEW_FAIL_X_PRESS @"EV_FLOW_RESULT_VIEW_SUCCESS_X_PRESS"

//WEB
#define EV_ACTIVITY_MARKET_ENTER_ALL @"EV_ACTIVITY_MARKET_ENTER_ALL"
#define EV_ACTIVITY_MARKET_EDIT_VOIP_ENTER @"EV_ACTIVITY_MARKET_EDIT_VOIP_ENTER"
#define EV_ACTIVITY_MARKET_FLOW_EDIT_ENTER @"EV_ACTIVITY_MARKET_FLOW_EDIT_ENTER"
#define EV_ACITIVYT_MARKET_PERSONAL_CENER_ENTER @"EV_ACITIVYT_MARKET_PERSONAL_CENER_ENTER"
#define EV_ACITIVYT_MARKET_NOTIFICATION_FLOW_CALL_ENTER @"EV_ACITIVYT_MARKET_NOTIFICATION_ENTER"
#define EV_ACITIVYT_MARKET_NOTIFICATION_INTERNATIONAL_ROMAING_ENTER @"EV_ACITIVYT_MARKET_NOTIFICATION_INTERNATIONAL_ROMAING_ENTER"

//package_path
#define EV_PACKAGE_PATH  @"path_share_package"
