include theos/makefiles/common.mk

TPDialerTweak_FRAMEWORKS =UIKit CoreTelephony SystemConfiguration CoreFoundation
TWEAK_NAME = TPDialerTweak
TPDialerTweak_FILES = Tweak.xm

LDFLAGS =  -lTPDialerAdvanced -lsqlite3 -lz

include $(THEOS_MAKE_PATH)/tweak.mk
