#ifdef TARGET_IPHONE

#define PJ_CONFIG_IPHONE 1

#define PJMEDIA_HAS_G729_CODEC 1
#define PJMEDIA_HAS_G722_CODEC 0
#define PJMEDIA_HAS_SPEEX_CODEC 0
#define PJMEDIA_HAS_G711_CODEC 0
#define PJMEDIA_HAS_GSM_CODEC 0
#define PJMEDIA_HAS_ILBC_CODEC 1
#define PJMEDIA_HAS_G7221_CODEC 0
#define PJMEDIA_HAS_L16_CODEC 0

#define PJSIP_DONT_SWITCH_TO_TCP 1
#define PJMEDIA_HAS_SRTP 0

#define PJMEDIA_HAS_OPUS_CODEC   1

#define PJSIP_MAX_PKT_LEN         10000

#include <pj/config_site_sample.h>

#elif defined(TARGET_ANDROID)

#define PJ_CONFIG_ANDROID 1

#define PJMEDIA_HAS_G729_CODEC 1
#define PJMEDIA_HAS_G722_CODEC 0
#define PJMEDIA_HAS_SPEEX_CODEC 0
#define PJMEDIA_HAS_G711_CODEC 0
#define PJMEDIA_HAS_GSM_CODEC 0
#define PJMEDIA_HAS_ILBC_CODEC 1
#define PJMEDIA_HAS_G7221_CODEC 0
#define PJMEDIA_HAS_L16_CODEC 0

#define PJSIP_DONT_SWITCH_TO_TCP 1

#define PJMEDIA_HAS_OPUS_CODEC   1

#define PJSIP_MAX_PKT_LEN         10000

#include <pj/config_site_sample.h>

//#undef PJMEDIA_HAS_G722_CODEC
//#define PJMEDIA_HAS_G722_CODEC 			1


#undef PJMEDIA_AUDIO_DEV_HAS_PORTAUDIO
#undef PJMEDIA_AUDIO_DEV_HAS_WMME
#undef PJMEDIA_AUDIO_DEV_HAS_COREAUDIO
#undef PJMEDIA_AUDIO_DEV_HAS_OPENSL
#undef PJMEDIA_AUDIO_DEV_HAS_ANDROID_JNI

#define PJMEDIA_AUDIO_DEV_HAS_PORTAUDIO		0
#define PJMEDIA_AUDIO_DEV_HAS_WMME		0
#define PJMEDIA_AUDIO_DEV_HAS_COREAUDIO		0
#define PJMEDIA_AUDIO_DEV_HAS_OPENSL        1
#define PJMEDIA_AUDIO_DEV_HAS_ANDROID_JNI	0

#define PJMEDIA_AUDIO_DEV_HAS_BDIMAD		0
//#define PJSIP_ENCODE_SHORT_HNAME 1
//#define PJSIP_INCLUDE_ALLOW_HDR_IN_DLG 0
//#define PJMEDIA_ADD_RTPMAP_FOR_STATIC_PT 0
//#define PJMEDIA_ADVERTISE_RTCP 0
#define PJMEDIA_HAS_SRTP 0

#else

#define PJMEDIA_HAS_G729_CODEC 0
#define PJMEDIA_HAS_G722_CODEC 0
#define PJMEDIA_HAS_SPEEX_CODEC 0
#define PJMEDIA_HAS_G711_CODEC 0
#define PJMEDIA_HAS_GSM_CODEC 0
#define PJMEDIA_HAS_ILBC_CODEC 0
#define PJMEDIA_HAS_G7221_CODEC 0
#define PJMEDIA_HAS_L16_CODEC 0

#define PJSIP_DONT_SWITCH_TO_TCP 1

#define PJMEDIA_HAS_OPUS_CODEC   1

#define PJSIP_MAX_PKT_LEN         10000

#define PJMEDIA_AUDIO_DEV_HAS_PORTAUDIO		0
#define PJMEDIA_AUDIO_DEV_HAS_WMME		0
#define PJMEDIA_AUDIO_DEV_HAS_COREAUDIO		0
#define PJMEDIA_AUDIO_DEV_HAS_OPENSL        0

#define PJMEDIA_AUDIO_DEV_HAS_BDIMAD		0

#define PJMEDIA_HAS_SRTP 0

#endif
