//
//  PushConstant.h
//  TouchPalDialer
//
//  Created by tanglin on 15-8-4.
//
//
#import "IndexConstant.h"

#ifndef TouchPalDialer_PushConstant_h
#define TouchPalDialer_PushConstant_h

#define XINGE_DEVICE_TOKEN                        @"XINGE_DEVICE_TOKEN"
#define XINGE_USER_ID                             @"XINGE_USER_ID"
#define XINGE_ADDUSER_SUCCESS                     @"XINGE_ADDUSER_SUCCESS"
#define ADVERTISEMENT @"advertisment"

#define XINGE_REGISTER_DEBUG_DEVICE_URL @"%@/yellowpage/getuiadduser"

#define XINGE_REGISTER_DEVICE_URL @"%@/yellowpage/getuiadduser"

#define QUERY_PUBLIC_NUMBER_MSG @"%@/message/query"
#define QUERY_PUBLIC_NUMBER_MSG_DEBUG @"%@/message/query"

#define QUERY_PUBLIC_NUMBER_INFO @"%@/fuwuhao/subscribed"
#define QUERY_PUBLIC_NUMBER_INFO_DEBUG @"%@/fuwuhao/subscribed"
#define QUERY_PUBLIC_NUMBER_INFO_SERVICE_ID @"%@/fuwuhao/info"
#define REQUEST_DATA_COUNT 5
#define REQUEST_MSG_DATA_COUNT 20

#define LIST_ITEM_FUWUHAO_TAG 1
#define LIST_ITEM_FUWUHAO_DETAIL_TAG 2

#define LIST_ITEM_ROW_HEIGHT 64

#define LIST_ITEM_LOGO_MARGIN_TOP 12
#define LIST_ITEM_LOGO_MARGIN_LEFT 15
#define LIST_ITEM_TIME_WIDTH 58
#define LIST_ITEM_RED_POINT_RADIUS 7

#define LIST_ITEM_TITLE_SIZE 17.0f
#define LIST_ITEM_SUB_TITLE_SIZE 12.0f
#define LIST_ITEM_TIME_SIZE 11.0f


#define LIST_ITEM_TITLE_TEXT_COLOR @"#ff333333"
#define LIST_ITEM_SUB_TITLE_TEXT_COLOR @"#ff999999"
#define LIST_ITEM_TIME_TEXT_COLOR @"#ff999999"
#define PUBLIC_NUMBER_LIST_BG_COLOR @"#fff8f8f8"

#define LIST_ITEM_BG_HIGHLIGHT_COLOR @"#edebeb"
#define LIST_ITEM_REDPOINT_BG_HIGHLIGHT_COLOR @"#ffef4845"

#define MSG_ITEM_TITLE_MARGIN_TOP 10
#define MSG_ITEM_TITLE_MARGIN_LEFT 10
#define MSG_ITEM_TITLE_HEIGHT 50

#define MSG_ITEM_DESC_MARGIN_TOP 10
#define MSG_ITEM_DESC_MARGIN_LEFT 10
#define MSG_ITEM_DESC_HEIGHT 50

#define MSG_ITEM_AREA_MARGIN_TOP 10
#define MSG_ITEM_AREA_MARGIN_LEFT 10
#define MSG_ITEM_AREA_HEIGHT 150

#define MSG_ITEM_REMARK_MARGIN_TOP 10
#define MSG_ITEM_REMARK_MARGIN_LEFT 10
#define MSG_ITEM_REMARK_HEIGHT 50

#define MSG_ITEM_DETAIL_MARGIN_TOP 10
#define MSG_ITEM_DETAIL_MARGIN_LEFT 10
#define MSG_ITEM_DETAIL_HEIGHT 50


//
#define MSG_ITEM_BG_DETAIL_MARGIN 12

#define MSG_ITEM_DETAIL_DATE_HEIGHT 60
#define MSG_ITEM_DETAIL_DATE_TEXT_COLOR @"#ffffffff"
#define MSG_ITEM_DETAIL_DATE_RECT_WIDTH 120
#define MSG_ITEM_DETAIL_DATE_RECT_HEIGHT 20
#define MSG_ITEM_DETAIL_TITLE_HEIGHT 40
#define MSG_ITEM_DETAIL_DESC_HEIGHT 30
#define MSG_ITEM_DETAIL_KEYNOTE_PER_HEIGHT 30
#define MSG_ITEM_DETAIL_REMARK_HEIGHT 30
#define MSG_ITEM_DETAIL_LEFT 15
#define MSG_ITEM_DETAIL_TOP 4
#define MSG_ITEM_DETAIL_MARGIN 10
#define MSG_ITEM_MORE_HEIGHT 43
#define MSG_ITEM_DETAIL_BORDER_COLOR @"#ffd5d5d5"
#define MSG_ITEM_SPERATE_BORDER_COLOR @"#ffd5d5d5"
#define MSG_ITEM_DETAIL_DATE_BG_COLOR @"#ffd5d5d5"
#define MSG_ITEM_KEYNOTE_TITLE_TEXT_COLOR @"#757575"
#define MSG_ITEM_MORE_TEXT_COLOR @"#333333"
#define MSG_ITEM_DETAIL_BG_COLOR @"#f0f0f0"
#define MSG_ITEM_TITLE_TOP 0
#define MSG_ITEM_DESC_TOP 8
#define MSG_ITEM_REMARK_TOP 12
#define MSG_ITEM_MARGIN_BOTTOM 40

#define MSG_ITEM_BG_COLOR @"#ffe3e3e3"


#define PUBLIC_NUMBER_BOTTOM_BAR_HEIGHT 50
#define PUBLIC_NUMBER_BOTTOM_HOME_BUTTOM_WIDTH 60
#define PUBLIC_NUMBER_BOTTOM_HOEM_TEXT_SIZE 8
#endif
