/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

//#import "MobilePhone-Structs.h"
#import "XXUnknownSuperclass.h" // Unknown library

@class UIImage, NSString;

@interface PhoneCall : XXUnknownSuperclass {
	CTCallRef _call;
	NSString* _displayName;
	NSString* _overrideName;
	unsigned _displayNameBreakPoint;
	int _abUid;
	NSString* _abLabel;
	UIImage* _image;
	struct {
		unsigned imageType : 2;
		unsigned abUidIsValid : 1;
		unsigned dialAssisted : 1;
		unsigned dialedFromEmergencyUI : 1;
		unsigned isEmergencyCall : 1;
	} _phoneCallFlags;
}
+(id)phoneCallForCall:(CTCallRef)call;
-(id)initWithCall:(CTCallRef)call;
-(void)dealloc;
-(int)_addressBookUid;
-(void)_handleIdentityChange;
-(void)_handleCallerIDChange;
-(void)_handleStatusChange;
-(CTCallRef)call;
-(int)status;
-(BOOL)isAlerting;
-(BOOL)isVoicemail;
-(BOOL)hold;
-(BOOL)unhold;
-(BOOL)isConferenced;
-(void)joinConference;
-(void)leaveConference;
-(void)disconnect;
-(id)number;
-(int)abUID;
-(id)_displayNameWithSeparator:(id)separator;
-(id)displayName;
-(id)multiLineDisplayName;
-(id)localizedLabel;
-(void)setOverrideName:(id)name;
-(BOOL)wasDialAssisted;
-(void)setWasDialAssisted:(BOOL)assisted;
-(BOOL)wasDialedFromEmergencyUI;
-(void)setWasDialedFromEmergencyUI:(BOOL)emergencyUI;
-(BOOL)isEmergencyCall;
-(id)_image;
-(id)desktopImage;
-(id)smallImage;
-(void)phoneApplicationAddressBookChangedNotification:(id)notification;
@end

